apiVersion: v1
kind: Service
metadata:
  name: doc-service
spec:
  selector:
    app: doc-app
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: frontend
    protocol: TCP
    port: 5173
    targetPort: 5173
  - name: ws
    protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-app
  template:
    metadata:
      labels:
        app: doc-app
    spec:
      containers:
      - name: doc-app
        image: siddjuugi/doc-repo:latest
        env:
        - name: DB_URL
          value: "postgres://pg-service.default:5432"
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: doc-config
              key: JWT_SECRET
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
        - containerPort: 5173
        - containerPort: 8081
      restartPolicy: Always
